name 'site-docstypo3org'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures site-docstypo3org'
long_description 'Installs/Configures site-docstypo3org'
version '0.1.0'
